### ISSUE TITLE
customize timer chain

### ISSUE THREAD

**Issue by DanielGennat** [DanielGennat/capstone-project#10]
**Value Proposition**
As a Musician I need custom timer intervals to be able to customize my individual exercise chain.

**Description**
![04 Edit Timer Chain Formular](https://user-images.githubusercontent.com/109812125/192535304-35b345f5-19c7-4be4-ae48-bee3ae132903.png)

**Acceptance Criteria**
- [x] a headline with "Edit Timer Chain!"
- [x] a form wich shows all timer intervals consecutively numbered
- [x] clicking on minutes or seconds the selected time is changeable
- [x] the input fields accept numbers between 0 and 59 only
- [x] 0 seconds are displayed as 00.
- [ ] every interval must be greater than 0
- [x] when clicking the apply button changes are applied and the edited timer chain starts counting down

**Tasks**
- [x] create a `<h2>` with "Edit Timer Chain!"
- [x] Create a `useState` for the timer intervals.
- [x] render a form with consecutively numbered input field pairs according to the current timer intervals
- [x] the input fields show the timer intervals in minutes and seconds
- [x] the input fields accept numbers between 0 and 59 only
- [x] 0 seconds are displayed as 00
- [ ] create a test to make sure that every countdown is greater than 0
- [ ] every input is required.
- [x] label the inputs with "min." and "sec."
- [x] create an apply button. `onSubmit` update the `useState` intervals according to the changes

**Comment by DanielGennat** [comment]
I have no idea for a useful split... Any suggestions? :)

**Comment by DanielGennat** [comment]
The countdown timer works with intervals of 0:00 so they don't have to be greater than 0. Wrote another test instead.
