### ISSUE TITLE
exercise names

### ISSUE THREAD

**Issue by DanielGennat** [DanielGennat/capstone-project#15]
**Value Proposition**
As a Musician I need the exercise names displayed to be able to know which is the current exercise and to have an overview.

**Description**
![list of exercises](https://user-images.githubusercontent.com/109812125/194884038-c0d82455-7599-4576-aab4-31e049dec754.png)

**Acceptance Criteria**
- [x] The timer chain is displayed with number, exercise name and time beneath the timer display
- [x] The current timer is highlighted
- [x] The edit timer chain form has labeled input fields for the exercise names

**Tasks**
- [x] add key-value pairs for the exercise name to every object of `timerChain`
- [x] render input fields for the exercise names in the `EditTimerChainForm` component
- [x] render a label with "exercise name" for each name input field
- [x] update the name input field in `newTimerChain`
- [x] render a list with id, name and time
- [x] write logic to highlight the current timer
