### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by DanielGennat** [DanielGennat/capstone-project#2]
**Value Proposition**
As a Musician I need a timer to be able to focus on an exercise for 5 minutes.

**Description**
![01 Timer](https://user-images.githubusercontent.com/109812125/191019197-d6b45eb9-faff-4f93-9309-10ee94e3dc20.png)

**Acceptance Criteria**
- [x] the timer starts counting down 5 minutes
- [x] when the timer has counted down an acoustic signal sounds

**Tasks**
- [x] initialize this project as a next-js project on your computer
- [x] install styled components.
- [x] create a branch
- [x] install react-countdown-circle-timer
- [x] create a countdown timer with a 5 minutes countdown
- [x] change the displayed remaining time to minutes and seconds
- [x] style the timer. Use a monospace font-familiy for the digits
- [x] `onComplete` an acoustic signal sounds
- [x] create a test for the audio notification

**Comment by MerleMak** [comment]
Hi Daniel, 
nice first user story!

Two comments to your tasks:
- I can recommend you to do some research on how to create a countdown timer in minutes and break down this task into a few more. It is a little bit more complex than a counter with whole numbers. 
- You included a sound signal into your Acceptance Criteria but you didn't include it into your tasks, please add this :)
Good job!

**Comment by macfrei** [comment]
Good job :) the second suggestion from Merle is not in your tasks yet. Maybe include it or leave it out entirely?

**Comment by MerleMak** [comment]
good job! :))
