### ISSUE TITLE
edit form page

### ISSUE THREAD

**Issue by DanielGennat** [DanielGennat/capstone-project#5]
**Value Proposition**
As a Musician I need a seperate edit page to be able to have a better overview.

**Description**
![03 Custom Timer Chain Formular](https://user-images.githubusercontent.com/109812125/191472383-05e2aeff-85eb-452b-96b8-c73f5f221d37.png)

**Acceptance Criteria**
- [x] when clicking on the edit button switch to the edit page
- [x] the edit page has the title "Edit Timer Chain!"
- [x] the page shows the edit form
- [x] when clicking the apply button changes are applied, the timer page is displayed and the edited timer chain starts counting down

**Tasks**
- [x] Create an edit page.
- [x] Move the form component to the edit page.
- [x] Create a fixed `<h2>` with "Edit Timer Chain!"
- [x] Change the apply button to an `<a>`. `onSubmit` update the `useState` intervals according to the changes.
- [x] Create an edit `<a>` and style it as button.
- [x] Create a routing for the edit link and the apply link.
- [x] Create a `404.js` with "page not found".

**Comment by StefanieLoeser** [comment]
Hi Daniel, looking pretty good already!
Just maybe it is a little too many steps for one user story? 
I saw you have tests also in the next story, maybe you move the test and the routing to the next one?

**Comment by DanielGennat** [comment]
Hi Stefanie, thanks for your review! Yes, it is pretty much. I considered that already. But for test driven development the test must be written in advance and without routing the user can not access the new function.
