### ISSUE TITLE
add more intervals

### ISSUE THREAD

**Issue by DanielGennat** [DanielGennat/capstone-project#6]
**Value Proposition**
As a Musician I need an adding function to be able to to increase the number of exercises.

**Description**
![04 add more intervals](https://user-images.githubusercontent.com/109812125/191476971-a5d1cedc-9b08-4ef1-a624-2a1e9a5c7d1f.png)

**Acceptance Criteria**
- [x] When clicking the add button a new timer interval appears. The default time is 5 minutes.

**Tasks**
- [x] Create an add button. `onClick` add a new 5 minutes interval to the timer intervals.
- [x] Write a test for the intervals update.

**Comment by StefanieLoeser** [comment]
see comment on previous user-story :)
