### ISSUE TITLE
local storage

### ISSUE THREAD

**Issue by DanielGennat** [DanielGennat/capstone-project#7]
**Value Proposition**
As a Musician I need a storage to be able to reuse my edited timer chain.

**Description**

**Acceptance Criteria**
- [ ] reloading the page the edited timer is still present
- [ ] if loading the storage fails 

**Tasks**
- [ ] Write a test for the page reload.
- [ ] Create a local storage.
- [ ] `onSubmit` the edited timer chain will be stored.
- [ ] Set the stored chain as default for the page load.
- [ ] Set a fallback chain.
- [ ] Create an error catch with `try`.
