### ISSUE TITLE
End Notification

### ISSUE THREAD

**Issue by DanielGennat** [DanielGennat/capstone-project#9]
**Value Proposition**
As a Musician I need an end notification to be able to notice the end of the timer chain.

**Description**
![02 End Notification](https://user-images.githubusercontent.com/109812125/192529025-9061a7c6-e790-4c04-9cef-8fc94720c6e9.png)

**Acceptance Criteria**
- [ ] When the last timer expires I get a text notification.
- [ ] When the last timer expires I get a different sound notification.

**Tasks**
- [ ] write logic to identify the last timer
- [ ] when `remainingTime`of the last timer is 0 display an end notification
- [ ] when `remainingTime`of the last timer is 0 play the `endSoundNotification`
